name: Docker Image Build Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "test" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image to test Dockerfile
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Docker/Dockerfile
        push: false
